name: golang

on:
    push:
        branches:
            - main
            - first-iter
        tags:
            - "v*.*.*"
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        container: golang:1.22.1
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: setup
              run: go mod tidy

            - name: run test
              run: GOOS=linux GOARCH=amd64 go test ./...

            - name: vet
              run: go vet ./...

    deploy:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        needs: test
        if: startsWith(github.ref, 'refs/tags')
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up Docker buildx
          uses: docker/setup-buildx-action@v3

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5.5.1
          with:
            images: ${{ secrets.DOCKER_USERNAME }}/ci-cd

        - name: Build and push Docker Inage
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
